all:
  vars:
    ansible_connection: ssh
    ansible_user: franz
    ansible_become: true

    kafka_version: "2.13-4.0.0"
    cluster_id: a8cf4682-9c5a-46c4-83b9-db94b69aa9f8
    voters: "0@kitten0:9093,1@kitten1:9093,2@kitten2:9093"

kafka_controller:
  hosts:
    192.168.122.32:
      node_id: "0"
    192.168.122.33:
      node_id: "1"
    192.168.122.34:
      node_id: "2"

kafka_broker:
  hosts:
    192.168.122.32:
    192.168.122.33:
    192.168.122.34:

schema_registry:
  hosts:
    192.168.122.32:

# kafka_rest:
#   hosts:
#     192.168.122.33:

# ksql:
#   hosts:
#     192.168.122.33:

# kafka_connect:
#   hosts:
#     192.168.122.33:

# control_center:
#   hosts:
#     192.168.122.33:
