all:
  vars:
    ansible_connection: ssh
    ansible_user: franz
    ansible_become: true

    pwd: /home/aes/src/anzr/bg/knas

    confluent_common_repository_baseurl: https://localhost/

    debian_java_package_name: openjdk-17-jre-headless

    validate_hosts: false
    installation_method: archive
    confluent_package_version: "7.9.1"
    confluent_archive_file_source: "{{ pwd }}/files/confluent-community-7.9.1.tar.gz"
    confluent_archive_file_remote: false

    jolokia_enabled: true
    jolokia_url_remote: false
    jolokia_jar_url: "{{ pwd }}/files/jolokia-jvm-1.6.2-agent.jar"

    jmxexporter_enabled: true
    jmxexporter_url_remote: false
    jmxexporter_jar_url: "{{ pwd }}/files/jmx_prometheus_javaagent-0.12.0.jar"

    confluent_server_enabled: false
    confluent_cli_download_enabled: false

    # mTLS
    ssl_enabled: false
    #certificate_authority_expiration_days: 45
    #ssl_mutual_auth_enabled: true

    #kafka_version: "2.13-4.0.0"
    #cluster_id: a8cf4682-9c5a-46c4-83b9-db94b69aa9f8
    #voters: "0@knas0:9093,1@knas1:9093,2@knas2:9093"

kafka_controller:
  #vars:
  #  kafka_controller_listeners:
  hosts:
    192.168.122.41:
#      controller_node_id: "1"
#    192.168.122.42:
#      controller_node_id: "2"
#    192.168.122.43:
#      controller_node_id: "3"

kafka_broker:
  hosts:
    192.168.122.41:
#      broker_node_id: "100"
#    192.168.122.42:
#      broker_node_id: "101"
#    192.168.122.43:
#      broker_node_id: "102"

schema_registry:
  hosts:
    192.168.122.41:

# kafka_rest:
#   hosts:
#     192.168.122.42:

# ksql:
#   hosts:
#     192.168.122.42:

# kafka_connect:
#   hosts:
#     192.168.122.42:

# control_center:
#   hosts:
#     192.168.122.42:
