- name: Install Apache Kafka
  hosts: all
  roles:
    - anzr.kafka.kafka

- name: Install Kafka controller
  hosts: kafka_controllers
  roles:
    - anzr.kafka.controller

- name: Install Kafka broker
  hosts: kafka_brokers
  roles:
    - anzr.kafka.broker
