- name: "Include JRE"
  include_role:
    name: "jre"

- name: "Roll out Kafka tarball"
  ansible.builtin.unarchive:
    dest: "/opt"
    src: "files/kafka_{{ kafka_version }}.tgz"
    creates: "/opt/kafka_{{ kafka_version }}"

- name: Symlink Kafka dir
  ansible.builtin.file:
    dest: "/opt/kafka"
    src: "/opt/kafka_{{ kafka_version }}"
    state: link
