- name: Ensure Kafka storage directory present
  file:
    dest: "{{ kafka_log_dir }}"
    state: directory

- name: Set cluster id
  ansible.builtin.command:
    argv:
      - /opt/kafka/bin/kafka-storage.sh
      - format
      - "--config={{ kafka_config }}"
      - "--cluster-id={{ cluster_id }}"
      - "--ignore-formatted"
  register: format
  changed_when: |
    "All of the log directories are already formatted." not in format.stdout
