- name: "Include Kafka"
  include_role:
    name: "kafka"

- name: Ensure Kafka configuration directory present
  file:
    dest: /etc/kafka
    state: directory

- name: Install broker properties
  ansible.builtin.copy:
    dest: /etc/kafka/broker-server.properties
    mode: "0644"
    owner: root
    group: root
    content: |
      node.id={{ broker_node_id }}
      process.roles=broker
      controller.quorum.voters={{ voters }}
      controller.listener.names=CONTROLLER

      listeners=PLAINTEXT://{{ ansible_host }}:9092
      listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      inter.broker.listener.name=PLAINTEXT

      log.dirs=/var/lib/kafka-broker-logs

      # num.network.threads=3
      # num.io.threads=8

      # log.retention.hours=168
      # log.segment.bytes=1073741824
      # log.retention.check.interval.ms=300000

      # offsets.topic.replication.factor=1
      # transaction.state.log.replication.factor=1
      # transaction.state.log.min.isr=1

- name: "Include storage"
  include_role:
    name: "storage"
  vars:
    kafka_config: /etc/kafka/broker-server.properties
    kafka_log_dir: /var/lib/kafka-broker-logs
