name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Run build
        run: bash ./build-dist.sh

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          title: "${{ env.VERSION }}"
          tag: "${{ env.VERSION }}"
